#!/usr/bin/env python3

from rich.console import Console
from rich.markdown import Markdown
import sys

if len(sys.argv) != 2:
  sys.exit(f"usage: {sys.argv[0]} filename")

filename = sys.argv[1]
with open(filename) as file:
    markdown = Markdown(file.read())
console = Console()
console.print(markdown)
